CREATE DATABASE BBDDProyecto;

-- Estructura de FACT_PROV

CREATE TABLE `FACT_PROV` (
  `CIF_PROVEEDOR` varchar(30) NOT NULL,
  `RAZ_PROVEEDOR` varchar(30) NOT NULL,
  `NUM_FACTURA` varchar(30) NOT NULL,
  `DES_FACTURA` varchar(30) NOT NULL,
  `BAS_IMPONIBLE` double(10,3) NOT NULL,
  `IVA_IMPORTE` double(10,3) NOT NULL,
  `TOT_IMPORTE` double(10,3) NOT NULL,
  `FEC_FACTURA` date NOT NULL,
  `FEC_VENCIMIENTO` date NOT NULL
) ;


-- Estructura de PROV_COMP


CREATE TABLE `PROV_COMP` (
  `CIF_PROVEEDOR` varchar(30) NOT NULL,
  `RAZ_PROVEEDOR` varchar(30) NOT NULL,
  `REG_NOTARIAL` varchar(30) NOT NULL,
  `SEG_RESPONSABILIDAD` varchar(30) NOT NULL,
  `SEG_IMPORTE` double(10,3) NOT NULL,
  `FEC_HOMOLOGACIÓN` date NOT NULL
) ;


-- Índices 
ALTER TABLE `FACT_PROV`
  ADD PRIMARY KEY (`NUM_FACTURA`),
  ADD KEY `FK_PROVEEDOR` (`CIF_PROVEEDOR`);


ALTER TABLE `PROV_COMP`
  ADD PRIMARY KEY (`CIF_PROVEEDOR`);


ALTER TABLE `FACT_PROV`
  ADD CONSTRAINT `FK_PROVEEDOR` FOREIGN KEY (`CIF_PROVEEDOR`) REFERENCES `PROV_COMP` (`CIF_PROVEEDOR`) ON DELETE CASCADE ON UPDATE CASCADE;

